version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install -g @angular/cli@6.0.0
  build:
    commands:
      - ng build --prod
  post_build:
    files:
      - "**/*"
    discard-paths: no
    base-directory: dist/william-library
